### ISSUE TITLE
执行 ansible-playbook fisco_bcos.yml 时报错

### ISSUE THREAD

**Issue by Gavin1216** [newtouch-cloud/ansible-for-fisco-bcos#13]
系统环境是，centos7.6，ansible2.10.4。
在安装好ansible环境，下载本项目源码后，
在执行 ansible-playbook fisco_bcos.yml 时报错，如下。
![image](https://user-images.githubusercontent.com/38353736/101782241-bb7f8700-3b33-11eb-8bf6-106aa0e2b091.png)

谢谢！

**Comment by Gavin1216** [comment]
图片无法显示，实际内容如下：
root@iZbp14vu541eobisc2ngynZ:~/ansible-fisco/ansible-for-fisco-bcos# ansible-playbook fisco_bcos.yml
/usr/local/lib/python2.7/dist-packages/ansible/parsing/vault/__init__.py:44: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.exceptions import InvalidSignature

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
Thursday 10 December 2020  22:01:35 +0800 (0:00:00.029)       0:00:00.029 ***** 
[DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host localhost should use 
/usr/bin/python3, but is using /usr/bin/python for backward compatibility with 
prior Ansible releases. A future Ansible release will default to using the 
discovered platform python for this host. See https://docs.ansible.com/ansible/
2.10/reference_appendices/interpreter_discovery.html for more information. This
 feature will be removed in version 2.12. Deprecation warnings can be disabled 
by setting deprecation_warnings=False in ansible.cfg.
ok: [localhost]

TASK [fisco_bcos : 非国密版 | 检查 generator 目录] *************************************
Thursday 10 December 2020  22:01:36 +0800 (0:00:01.771)       0:00:01.801 ***** 
ok: [localhost] => (item=/root/ansible-fisco/ansible-for-fisco-bcos/inventories/sample/deploy/generator/dir_agency_ca)
ok: [localhost] => (item=/root/ansible-fisco/ansible-for-fisco-bcos/inventories/sample/deploy/generator/dir_chain_ca)

TASK [fisco_bcos : 国密版 | 检查 generator 目录] **************************************
Thursday 10 December 2020  22:01:37 +0800 (0:00:00.525)       0:00:02.326 ***** 

TASK [fisco_bcos : 如果 generator 目录内容不完整，则中止执行。] ********************************
Thursday 10 December 2020  22:01:37 +0800 (0:00:00.080)       0:00:02.406 ***** 
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'true in __generator_dir.results | map(attribute='stat.exists')' failed. The error was: error while evaluating conditional (true in __generator_dir.results | map(attribute='stat.exists')): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/root/ansible-fisco/ansible-for-fisco-bcos/roles/fisco_bcos/tasks/pre_tasks.yml': line 38, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: 如果 generator 目录内容不完整，则中止执行。\n  ^ here\n"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

Thursday 10 December 2020  22:01:37 +0800 (0:00:00.035)       0:00:02.442 ***** 
=============================================================================== 
gather_facts ------------------------------------------------------------ 1.77s
fisco_bcos -------------------------------------------------------------- 0.64s
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
total ------------------------------------------------------------------- 2.41s

**Comment by bottlelee** [comment]
你好，抱歉回复迟了。
请更新一下最新的代码再试试，另外 `inventories/v2.7.0/group_vars/all/all.yml` 文件里有个 `# ansible_python_interpreter: python3` 的设置，请取消注释，强制使用 python3 作为执行环境。

如果问题依然存在，请再反馈给我。我明天建个虚拟机看能不能重现你说的问题。

谢谢你的使用和反馈。

**Comment by Gavin1216** [comment]
谢谢！我先试试！

**Comment by Gavin1216** [comment]
已测试，问题得到解决，谢谢！

**Comment by bottlelee** [comment]
多谢关注，希望我们的项目能帮助到你们。
