### ISSUE TITLE
已有机构生成扩展节点后，新节点启动失败

### ISSUE THREAD

**Issue by longdacao** [newtouch-cloud/ansible-for-fisco-bcos#17]
错误原因如下：
1 ） 扩展节点 的 conf 目录下没有生产 node.nodeid,  node.key 这两个文件，导致直接启动失败
2） 新生成的机构节点，没有考虑现有机构节点的端口占用，还是从 20200, 8545, 30300 这些端口开始 
3）扩展节点中的 config.ini 文件中，p2p 的信息有缺失，比如，这个 192.168.0.175 是新增加的机构节点。然后在新生成节点的 config.ini 文件中，发现信息有缺失，没有加入 192.168.0.228 这个现有节点的 P2P 信息
4） 最后一点需要说明的是，如果配置都没有问题的，节点也启动成功的话，新增加的这个节点默认也是不会进行共识的，因为新增节点默认是游离节点

**Comment by bottlelee** [comment]
Fixed by #18 #19 #20
